### ISSUE TITLE
`JTabbedPane` throws `NullPointerException`

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#125]
```
2023-02-28 09:35:54.003 ERROR [AWT-EventQueue-0] listfix.view.GUIScreen - Uncaught Exception
java.lang.NullPointerException: Cannot invoke "javax.swing.JTabbedPane.getLayout()" because "this.tabPane" is null
	at javax.swing.plaf.basic.BasicTabbedPaneUI.scrollableTabLayoutEnabled(Unknown Source) ~[?:?]
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabContainer.doLayout(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validateTree(Unknown Source) ~[?:?]
	at java.awt.Container.validate(Unknown Source) ~[?:?]
	at javax.swing.SwingUtilities.updateComponentTreeUI(Unknown Source) ~[?:?]
	at listfix.view.GUIScreen.updateAllComponentTreeUIs(GUIScreen.java:1700) ~[listFix.exe:2.6.0-11]
	at listfix.view.GUIScreen.setApplicationFont(GUIScreen.java:2603) ~[listFix.exe:2.6.0-11]
	at listfix.view.GUIScreen.fireOptionsPopup(GUIScreen.java:603) ~[listFix.exe:2.6.0-11]
	at listfix.view.GUIScreen._appOptionsMenuItemActionPerformed(GUIScreen.java:2232) ~[listFix.exe:2.6.0-11]
	at listfix.view.GUIScreen.lambda$initComponents$26(GUIScreen.java:1056) ~[listFix.exe:2.6.0-11]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:?]
	at javax.swing.AbstractButton.doClick(Unknown Source) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[?:?]
	at java.awt.Component.processMouseEvent(Unknown Source) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:?]
	at java.awt.Component.processEvent(Unknown Source) ~[?:?]
	at java.awt.Container.processEvent(Unknown Source) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:?]
```	
Reported [here](https://github.com/Borewit/listFix/pull/106#issuecomment-1447766355)

**Comment by Borewit** [comment]
I assume one is already resolved @touwys, do you agree to close this?

**Comment by touwys** [comment]
> I assume one is already resolved

I can safely say only that I have not seen the error again afterwards. 🙃 Based on that premise, we can close it.
