### ISSUE TITLE
listFix() distribution does not generate log file

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#238]
The log files location can not be located in the user profile:

    
   ![Screenshot User Profile Directory_2](https://github.com/Borewit/listFix/assets/65730626/9513901b-0732-4206-a20a-0ced7272db94)

_Originally posted by @touwys in https://github.com/Borewit/listFix/issues/229#issuecomment-1807105389_

**Comment by Borewit** [comment]
This problem only occurs in the the jpackage image, which makes it very hard to debug.
When the Windows console mode is activated (6419c9cbe3764b13157576ec74114dd71c0cdf60) in the build, the following error occurs:

```
ERROR StatusLogger Unable to load services for service class org.apache.logging.log4j.spi.Provider
 java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: module listFix.merged.module does not declare `uses`
        at java.base/java.util.ServiceLoader.fail(Unknown Source)
        at java.base/java.util.ServiceLoader.checkCaller(Unknown Source)
        at java.base/java.util.ServiceLoader.<init>(Unknown Source)
        at java.base/java.util.ServiceLoader.load(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ServiceLoaderUtil.callServiceLoader(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ServiceLoaderUtil$ServiceLoaderSpliterator.<init>(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ServiceLoaderUtil.loadClassloaderServices(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ProviderUtil.<init>(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ProviderUtil.lazyInit(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.util.ProviderUtil.hasProviders(Unknown Source)
        at listFix.merged.module@3.0.1.6/org.apache.logging.log4j.LogManager.<clinit>(Unknown Source)
        at listFix.app/listfix.view.GUIScreen.<clinit>(Unknown Source)
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception while removing reference.
```
Which looks similar to to this issue: beryx/badass-jlink-plugin#228
